### PR TITLE
Support Private AKS cluster

### LINKED ISSUE #1692: [Feature] Support privated AKS cluster during liqoctl install
**Is your feature request related to a problem? Please describe.**
With Private AKS cluster we are not able to use liqoctl install command to install liqo or generate `values.yaml` file due to `fqdn` is not present in AKS Get API
`cluster, err := aksClient.Get(ctx, o.resourceGroupName, o.resourceName)`

**Describe the solution you'd like**
We can pass fqdn during the install command and liqoctl should use the one passed on via arguments
`liqoctl install aks .... --fqdn=https://xxxxx:443`
I have made the changes to support this feature in my feature branch, if this is useful I'll open PR.

**Describe alternatives you've considered**

**Additional context**
Error I get from current liqoctl install command
```
 INFO  Installer initialized                                                                                                         
 ERRO  Error retrieving provider specific configuration: failed retrieving cluster information: failed to retrieve cluster APIServer FQDN, is the cluster running?
```

### PR DESCRIPTION
**Pull request by Sharathmk99**
# Description

Fixes #1692

# How Has This Been Tested?

```
liqoctl install aks --only-output-values --sharing-percentage=100 --cluster-labels=cluster=aks-kubenet-cni --cluster-name=aks-kubenet-cni --set=auth.service.type=NodePort --set gateway.service.type=NodePort --set storage.enable=false --set telemetry.enable=false --resource-group-name xxx --resource-name xxx --subscription-id xxx --subscription-name xxxt --fqdn=https://xxxx.privatelink.eastus.azmk8s.io:443
```

- [x] Tested with private AKS cluster

### CODE REVIEW

**Comment by Sharathmk99** [comment]
@aleoli  can you please review this PR?

**Comment by aleoli** [comment]
Hi @Sharathmk99! Sure, I will review it as soon as possible, I’m sorry but we had some trouble with the ci runners in the last few days

**Comment by Sharathmk99** [comment]
> Hi @Sharathmk99! Sure, I will review it as soon as possible, I’m sorry but we had some trouble with the ci runners in the last few days

No problem. Thank you

**Comment by aleoli** [comment]
Hi @Sharathmk99! The pr looks good to me.

Can you please squash your commits to make only one?

**Comment by Sharathmk99** [comment]
> Hi @Sharathmk99! The pr looks good to me.
> 
> Can you please squash your commits to make only one?

Done. Please approve the CI workflow. Thanks

**Review by aleoli — APPROVED** [review]

**Pull request merged**
