### PR TITLE
add tags

### PR DESCRIPTION
**Pull request by tsusadivyago**
# Description

First Time Contributor

I want to add tags to IAM user.

# How Has This Been Tested? 

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

Not Tested.

I am trying to figure out how to create docker images for local development testing

### CODE REVIEW

**Comment by frisso** [comment]
@tsusadivyago Is this PR still active? Thanks!

**Comment by cheina97** [comment]
Closing for inactivity

**Pull request closed without merging**
