### PR TITLE
Changing family and version of network API

### PR DESCRIPTION
**Pull request by alacuku**
# Description
Changing family of network API from `liqonet.liqo.io` to `net.liqo.io` and version from `v1` to `v1alpha1`.
Updating documentation and install scripts to use the label `net.liqo.io/gateway=true` instead of `liqonet.liqo.io/gateway=true`

### CODE REVIEW

**Comment by frisso** [comment]
Why there are still many "v1" strings (instead of "v1alpha") in the code?

**Comment by alacuku** [comment]
> Why there are still many "v1" strings (instead of "v1alpha") in the code?

Can you give me a pointer to those "v1" strings, please?

**Review by palexster — APPROVED** [review]

**Review by fraborg — APPROVED** [review]

**Comment by frisso** [comment]
> > Why there are still many "v1" strings (instead of "v1alpha") in the code?
> 
> Can you give me a pointer to those "v1" strings, please?

internal/crdReplicator/crdReplicator-config_test.go#L14

**Review by palexster — APPROVED** [review]

**Pull request merged**
