### PR TITLE
README: fix broken image

### PR DESCRIPTION
**Pull request by frisso**
Replace a broken image in the main README file with a markdown emoji.

### CODE REVIEW

**Comment by giorio94** [comment]
Oops, my fault I believe.

Honestly, I was wondering whether it is worth keeping that icon, as (a) most likely the problem will happen again in the future, (b) it adds practically no value and, by the way, (c) it is completely invisible with the dark theme.

Alternatively, we could use the markup emoji `:bell:` 🔔, that, although a bit different, would make the README self-contained (and works regardless of the theme).

**Comment by frisso** [comment]
Completely fine with your proposal, Marco.
Please, discard my changes and go with the :bell:

**Review by aleoli — APPROVED** [review]

**Pull request merged**
