### PR TITLE
Updated ROADMAP for the next (0.11) release

### PR DESCRIPTION
**Pull request by frisso**

### CODE REVIEW

**Comment by Sharathmk99** [comment]
Can we include #1831 #1846 #1768 please?

**Comment by aleoli** [comment]
Hi @Sharathmk99, this roadmap is for the next release that will be ready soon. We will include these features in future releases.

The VirtualNode feature is 90% available in the current Liqo version; we need to refactor the authentication workflow to complete it; we will include it in the roadmap for the subsequent releases.

We cannot define a general model for the upgrading process yet, but we will probably provide a manual step-by-step guide for this release.

While for the "graceful" unpeer, we need to think a little about it to identify the best solution for integrating it.

**Review by cheina97 — APPROVED** [review]

**Comment by Sharathmk99** [comment]
> Hi @Sharathmk99, this roadmap is for the next release that will be ready soon. We will include these features in future releases.
> 
> The VirtualNode feature is 90% available in the current Liqo version; we need to refactor the authentication workflow to complete it; we will include it in the roadmap for the subsequent releases.
> 
> We cannot define a general model for the upgrading process yet, but we will probably provide a manual step-by-step guide for this release.
> 
> While for the "graceful" unpeer, we need to think a little about it to identify the best solution for integrating it.

Thank you so much for the reply.

**Pull request merged**
