### PR TITLE
Fix --offer-disable-auto-accept for controller manager

### PR DESCRIPTION
**Pull request by CapacitorSet**
# Description

Fix --offer-disable-auto-accept for controller manager (it is currently ignored due to a bug).

# How Has This Been Tested?

Tested by hand.

### CODE REVIEW

**Comment by giorio94** [comment]
Would suggest to add a unit test to ensure the function correctness.

**Comment by CapacitorSet** [comment]
I'm not sure how to fix this either. When debugging the tests I can see `resourceOffer.Status.Phase` reverting to "ManualActionRequired" immediately after the update which should set it to "Accepted".

I suppose it's something in the Kubernetes API that I'm missing?

**Pull request merged**
