### PR TITLE
"possible scenarios" hyperlink in readme does not work

### PR DESCRIPTION
**Pull request by filippoprojetto**
Fix broken link.

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
@palexster IIRC there was an automatic tool to check the links. Am I wrong or is it broken?

**Comment by palexster** [comment]
> @palexster IIRC there was an automatic tool to check the links. Am I wrong or is it broken?

Yes, it should have caught that one. Thanks @filippoprojetto!

**Review by palexster — APPROVED** [review]

**Pull request merged**
