### PR TITLE
Virtual kubelet: add liqo client and informers to reflection manager

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR extends the virtual kubelet reflection manager to introduce the support for the client and the informers specific for liqo resources.

Fixes #(issue)

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Unit tests (new + existing)
- [x] E2E tests (existing)

### CODE REVIEW

**Comment by giorio94** [comment]
rebase test=true

**Review by palexster — APPROVED** [review]

**Review by aleoli — APPROVED** [review]

**Pull request merged**
