### PR TITLE
Bump the k8s libraries to the latest version

### PR DESCRIPTION
**Pull request by giorio94**
# Description

This PR bumps the k8s libraries to the latest version, updating at the same time the automatically generated manifests which caused dependabot PR to fail linting.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [ ] Existing tests

### CODE REVIEW

**Comment by giorio94** [comment]
The new version of controller runtime has been released. Still, currently experiencing the same issue mentioned here: https://github.com/k8up-io/k8up/pull/783

**Comment by aleoli** [comment]
Continuing in https://github.com/liqotech/liqo/pull/1641

**Pull request closed without merging**
