### PR TITLE
Docs: external link refactoring

### PR DESCRIPTION
**Pull request by cheina97**
# Description

This PR refactor the documentation replacing external links with valid ones.
This avoids broken links or redirections.

### CODE REVIEW

**Comment by frisso** [comment]
Really, we had so many broken links?

**Review by aleoli — APPROVED** [review]

**Comment by cheina97** [comment]
> Really, we had so many broken links?

No, the only broken link is `https://docs.projectcalico.org/getting-started/kubernetes/flannel/flannel`, the other ones are old links that redirect to newer ones.

**Pull request merged**
