### PR TITLE
Disable Discovery Deployment

### PR DESCRIPTION
**Pull request by aleoli**
# Description

This pr disables the discovery component by default. It will be enabled if one of the following is true:

* the mDNS discovery is enabled
* the mDNS advertisement is enabled
* we are installing on a KinD cluster

# How Has This Been Tested?

- [x] locally

### CODE REVIEW

**Review by giorio94 — APPROVED** [review]
/lgtm

**Review by palexster — APPROVED** [review]

**Review by palexster — APPROVED** [review]

**Pull request merged**
