### PR TITLE
Extra tolerations for route daemonset

### LINKED ISSUE #1844: [Feature] Option to specify extra toleration in Helm chart for Route DaemonSet manifest
**Is your feature request related to a problem? Please describe.**
Option to specify extra toleration for Route DaemonSet manifest, as some of our nodes has taints. As our nodes have taints route pod doesn't get scheduled to tainted node which means routing doesn't work. Faced this problem and spent 2 days to debug and @cheina97 helped me to identify the same.

**Describe the solution you'd like**
Helm chart to provide option to add extra tolerations if nodes contains any taints.

**Describe alternatives you've considered**
Will open PR with the changes.

**Additional context**

### PR DESCRIPTION
**Pull request by Sharathmk99**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1844 

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Local K8S cluster

### CODE REVIEW

**Comment by Sharathmk99** [comment]
Unit test fails on go part, I think it's not related to my changes. Can someone help me?

**Comment by aleoli** [comment]
Hi @Sharathmk99, we have some issues related to unit tests: sometimes they are failing for no reason, and when re-runned they work (as in this case). Your pr cannot be the cause of the fail

**Review by aleoli — APPROVED** [review]

**Pull request merged**
